import { sql } from "drizzle-orm";
import { pgTable, text, varchar, timestamp, boolean, integer, decimal, jsonb, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// ================================================================
// ENUMS & CONSTANTS
// ================================================================

// User roles for B2B wholesale platform
export const UserRole = {
  ADMIN: 'admin',
  CUSTOMER: 'customer',
  PENDING: 'pending',
} as const;

export type UserRoleType = typeof UserRole[keyof typeof UserRole];

// User status for approval workflow
export const UserStatus = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  SUSPENDED: 'suspended',
} as const;

export type UserStatusType = typeof UserStatus[keyof typeof UserStatus];

// Order status
export const OrderStatus = {
  PENDING_APPROVAL: 'pending_approval',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
} as const;

export type OrderStatusType = typeof OrderStatus[keyof typeof OrderStatus];

// Product categories for wholesale
export const ProductCategory = {
  SUNGLASSES: 'sunglasses',
  CELLULAR: 'cellular',
  CAPS: 'caps',
  PERFUMES: 'perfumes',
  NOVELTY: 'novelty',
} as const;

export type ProductCategoryType = typeof ProductCategory[keyof typeof ProductCategory];

// AI event types for logging
export const AIEventType = {
  SEARCH: 'search',
  CART_BUILDER: 'cart_builder',
  INTAKE_SUMMARY: 'intake_summary',
  RISK_FLAG: 'risk_flag',
  CATALOG_ENRICHMENT: 'catalog_enrichment',
  REORDER_SUGGESTION: 'reorder_suggestion',
} as const;

export type AIEventTypeValue = typeof AIEventType[keyof typeof AIEventType];

// ================================================================
// USERS TABLE
// ================================================================

export const users = pgTable("users", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull().default(UserRole.PENDING),
  status: text("status").notNull().default(UserStatus.PENDING),
  
  // Business information
  businessName: text("business_name"),
  contactName: text("contact_name"),
  phone: text("phone"),
  
  // Address (for future phases)
  address: text("address"),
  city: text("city"),
  state: text("state"),
  zipCode: text("zip_code"),
  
  // Zoho integration
  zohoCustomerId: text("zoho_customer_id"),
  priceListId: text("price_list_id"), // Customer-specific pricing tier
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
  lastLoginAt: timestamp("last_login_at"),
});

// ================================================================
// PRODUCTS TABLE (Zoho Inventory Mapping)
// ================================================================

export const products = pgTable("products", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  
  // SKU and identification
  sku: text("sku").notNull().unique(),
  name: text("name").notNull(),
  description: text("description"),
  
  // Categorization
  category: text("category").notNull(), // sunglasses, cellular, caps, perfumes, novelty
  subcategory: text("subcategory"),
  brand: text("brand"),
  tags: text("tags").array(), // For AI search and filtering
  
  // Pricing (wholesale)
  basePrice: decimal("base_price", { precision: 10, scale: 2 }).notNull(),
  compareAtPrice: decimal("compare_at_price", { precision: 10, scale: 2 }), // MSRP
  minOrderQuantity: integer("min_order_quantity").default(1),
  casePackSize: integer("case_pack_size").default(1), // Units per case
  
  // Inventory
  stockQuantity: integer("stock_quantity").default(0),
  lowStockThreshold: integer("low_stock_threshold").default(10),
  isActive: boolean("is_active").default(true),
  
  // Media
  imageUrl: text("image_url"),
  imageUrls: text("image_urls").array(), // Multiple images
  
  // Zoho Integration
  zohoItemId: text("zoho_item_id"),
  zohoCategoryId: text("zoho_category_id"),
  zohoLastSyncAt: timestamp("zoho_last_sync_at"),
  
  // AI-enriched content (generated by AI, not pushed to Zoho without approval)
  aiTitle: text("ai_title"),
  aiBullets: text("ai_bullets").array(),
  aiTags: text("ai_tags").array(),
  aiEnrichedAt: timestamp("ai_enriched_at"),
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  categoryIdx: index("products_category_idx").on(table.category),
  skuIdx: index("products_sku_idx").on(table.sku),
  activeIdx: index("products_active_idx").on(table.isActive),
}));

// ================================================================
// CARTS TABLE
// ================================================================

export const carts = pgTable("carts", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id),
  
  // Metadata
  itemCount: integer("item_count").default(0),
  subtotal: decimal("subtotal", { precision: 10, scale: 2 }).default("0"),
  
  // AI Cart Builder metadata
  aiGenerated: boolean("ai_generated").default(false),
  aiPrompt: text("ai_prompt"), // Original prompt used to generate cart
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  userIdx: index("carts_user_idx").on(table.userId),
}));

// ================================================================
// CART ITEMS TABLE
// ================================================================

export const cartItems = pgTable("cart_items", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  cartId: varchar("cart_id", { length: 36 }).notNull().references(() => carts.id, { onDelete: "cascade" }),
  productId: varchar("product_id", { length: 36 }).notNull().references(() => products.id),
  
  quantity: integer("quantity").notNull().default(1),
  unitPrice: decimal("unit_price", { precision: 10, scale: 2 }).notNull(),
  lineTotal: decimal("line_total", { precision: 10, scale: 2 }).notNull(),
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  cartIdx: index("cart_items_cart_idx").on(table.cartId),
  productIdx: index("cart_items_product_idx").on(table.productId),
}));

// ================================================================
// ORDERS TABLE
// ================================================================

export const orders = pgTable("orders", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  orderNumber: text("order_number").notNull().unique(),
  userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id),
  
  // Status
  status: text("status").notNull().default(OrderStatus.PENDING_APPROVAL),
  
  // Totals
  subtotal: decimal("subtotal", { precision: 10, scale: 2 }).notNull(),
  taxAmount: decimal("tax_amount", { precision: 10, scale: 2 }).default("0"),
  shippingAmount: decimal("shipping_amount", { precision: 10, scale: 2 }).default("0"),
  totalAmount: decimal("total_amount", { precision: 10, scale: 2 }).notNull(),
  
  // Shipping address
  shippingAddress: text("shipping_address"),
  shippingCity: text("shipping_city"),
  shippingState: text("shipping_state"),
  shippingZipCode: text("shipping_zip_code"),
  
  // Admin workflow
  approvedBy: varchar("approved_by", { length: 36 }).references(() => users.id),
  approvedAt: timestamp("approved_at"),
  rejectedBy: varchar("rejected_by", { length: 36 }).references(() => users.id),
  rejectedAt: timestamp("rejected_at"),
  rejectionReason: text("rejection_reason"),
  
  // Internal notes (admin only)
  internalNotes: text("internal_notes"),
  
  // Zoho integration
  zohoSalesOrderId: text("zoho_sales_order_id"),
  zohoPushedAt: timestamp("zoho_pushed_at"),
  zohoIdempotencyKey: text("zoho_idempotency_key"), // For safe retries
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => ({
  userIdx: index("orders_user_idx").on(table.userId),
  statusIdx: index("orders_status_idx").on(table.status),
  orderNumberIdx: index("orders_order_number_idx").on(table.orderNumber),
}));

// ================================================================
// ORDER ITEMS TABLE
// ================================================================

export const orderItems = pgTable("order_items", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  orderId: varchar("order_id", { length: 36 }).notNull().references(() => orders.id, { onDelete: "cascade" }),
  productId: varchar("product_id", { length: 36 }).notNull().references(() => products.id),
  
  // Snapshot at time of order
  sku: text("sku").notNull(),
  productName: text("product_name").notNull(),
  
  quantity: integer("quantity").notNull(),
  unitPrice: decimal("unit_price", { precision: 10, scale: 2 }).notNull(),
  lineTotal: decimal("line_total", { precision: 10, scale: 2 }).notNull(),
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({
  orderIdx: index("order_items_order_idx").on(table.orderId),
}));

// ================================================================
// AI TABLES
// ================================================================

// Product embeddings for vector search
export const productEmbeddings = pgTable("product_embeddings", {
  sku: text("sku").primaryKey().references(() => products.sku),
  
  // Vector embedding (stored as JSON array for compatibility)
  // In production, consider pgvector extension for native vector support
  embedding: jsonb("embedding"), // Array of floats
  embeddingModel: text("embedding_model").default("text-embedding-3-small"),
  
  // Content used to generate embedding
  embeddedContent: text("embedded_content"), // Concatenated searchable text
  
  // Timestamps
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// AI response cache for cost control
export const aiCache = pgTable("ai_cache", {
  key: text("key").primaryKey(), // hash(user_id + feature + normalized_input + filters)
  
  // Cached response
  responseJson: jsonb("response_json").notNull(),
  
  // Feature metadata
  feature: text("feature").notNull(), // search, cart_builder, intake_summary, etc.
  
  // Expiration
  expiresAt: timestamp("expires_at").notNull(),
  
  // Stats
  hitCount: integer("hit_count").default(0),
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({
  featureIdx: index("ai_cache_feature_idx").on(table.feature),
  expiresIdx: index("ai_cache_expires_idx").on(table.expiresAt),
}));

// AI event logging for analytics and cost monitoring
export const aiEvents = pgTable("ai_events", {
  id: varchar("id", { length: 36 }).primaryKey().default(sql`gen_random_uuid()`),
  
  // User context
  userId: varchar("user_id", { length: 36 }).references(() => users.id),
  
  // Event details
  eventType: text("event_type").notNull(), // search, cart_builder, intake_summary, etc.
  feature: text("feature").notNull(),
  
  // Request/response metadata
  payloadJson: jsonb("payload_json"), // Input parameters
  responseJson: jsonb("response_json"), // AI response (truncated if large)
  
  // Cost tracking
  tokenEstimate: integer("token_estimate"),
  latencyMs: integer("latency_ms"),
  cacheHit: boolean("cache_hit").default(false),
  modelUsed: text("model_used"),
  
  // Error tracking
  errorMessage: text("error_message"),
  
  // Timestamps
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => ({
  userIdx: index("ai_events_user_idx").on(table.userId),
  eventTypeIdx: index("ai_events_type_idx").on(table.eventType),
  createdAtIdx: index("ai_events_created_idx").on(table.createdAt),
}));

// ================================================================
// ZOD SCHEMAS & TYPES
// ================================================================

// User schemas
export const insertUserSchema = createInsertSchema(users).pick({
  email: true,
  password: true,
  businessName: true,
  contactName: true,
  phone: true,
  address: true,
  city: true,
  state: true,
  zipCode: true,
}).extend({
  email: z.string().email("Please enter a valid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  businessName: z.string().optional(),
  contactName: z.string().optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zipCode: z.string().optional(),
});

export const loginSchema = z.object({
  email: z.string().email("Please enter a valid email address"),
  password: z.string().min(1, "Password is required"),
});

// Product schemas
export const insertProductSchema = createInsertSchema(products).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export const updateProductSchema = insertProductSchema.partial();

// Cart schemas
export const insertCartItemSchema = z.object({
  productId: z.string().uuid(),
  quantity: z.number().int().positive(),
});

// Order schemas
export const createOrderSchema = z.object({
  shippingAddress: z.string().optional(),
  shippingCity: z.string().optional(),
  shippingState: z.string().optional(),
  shippingZipCode: z.string().optional(),
});

// AI event schema
export const insertAIEventSchema = createInsertSchema(aiEvents).omit({
  id: true,
  createdAt: true,
});

// ================================================================
// TYPES
// ================================================================

export type InsertUser = z.infer<typeof insertUserSchema>;
export type LoginCredentials = z.infer<typeof loginSchema>;
export type User = typeof users.$inferSelect;
export type SafeUser = Omit<User, 'password'>;

export type Product = typeof products.$inferSelect;
export type InsertProduct = z.infer<typeof insertProductSchema>;

export type Cart = typeof carts.$inferSelect;
export type CartItem = typeof cartItems.$inferSelect;

export type Order = typeof orders.$inferSelect;
export type OrderItem = typeof orderItems.$inferSelect;

export type ProductEmbedding = typeof productEmbeddings.$inferSelect;
export type AICache = typeof aiCache.$inferSelect;
export type AIEvent = typeof aiEvents.$inferSelect;

// ================================================================
// HELPERS
// ================================================================

export function toSafeUser(user: User): SafeUser {
  const { password, ...safeUser } = user;
  return safeUser;
}

// Generate order number
export function generateOrderNumber(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `WH-${timestamp}-${random}`;
}

// Generate AI cache key
export function generateAICacheKey(
  feature: string,
  userId: string | null,
  input: string,
  filters?: Record<string, unknown>
): string {
  const normalized = input.toLowerCase().trim();
  const filterStr = filters ? JSON.stringify(filters) : '';
  const combined = `${feature}:${userId || 'anon'}:${normalized}:${filterStr}`;
  // Simple hash for cache key
  let hash = 0;
  for (let i = 0; i < combined.length; i++) {
    const char = combined.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return `${feature}_${Math.abs(hash).toString(36)}`;
}
